
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"
  bulk_max_size: 1024

setup.kibana:
  host: "kibana:5601"

setup.ilm.enabled: false
setup.ilm.rollover_alias: ""

setup.template.name: "app-logs"
setup.template.pattern: "app-logs-*"
setup.template.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"
